"""Refatoracao categorias despesa (nivel unico) e add Transferencias

Revision ID: 44efd7cbf8e4
Revises: 6d1ad4eb1ae4
Create Date: 2025-12-16 21:09:19.948061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44efd7cbf8e4'
down_revision = '6d1ad4eb1ae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Adiciona a nova tabela Transfer
    op.create_table('transfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('source_wallet_id', sa.Integer(), nullable=False),
    sa.Column('target_wallet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_wallet_id'], ['wallet.id'], ),
    sa.ForeignKeyConstraint(['target_wallet_id'], ['wallet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # 2. Renomeia a tabela 'expense_item' para 'expense_category' para preservar os dados.
    op.rename_table('expense_item', 'expense_category')

    # 3. Remove a coluna group_id e sua Foreign Key associada da nova tabela expense_category
    with op.batch_alter_table('expense_category', schema=None) as batch_op:
        # A drop_column em modo batch deve resolver a FK para expense_group
        batch_op.drop_column('group_id') 

    # 4. Ajusta a tabela 'expense' (Tabela dependente)
    with op.batch_alter_table('expense', schema=None) as batch_op:
        
        # 4a. Renomeia a coluna 'item_id' para 'category_id'. (PRESERVA VALORES)
        batch_op.alter_column('item_id', new_column_name='category_id', existing_type=sa.Integer(), nullable=False)

        # 4b. CRÍTICO: Cria a nova Foreign Key COM NOME EXPLÍCITO.
        # Este nome pode variar, mas 'op.f(...)' é o padrão recomendado pelo Alembic.
        batch_op.create_foreign_key(op.f('fk_expense_category_id_expense_category'), 'expense_category', ['category_id'], ['id'])

    # 5. AGORA, remove a tabela 'expense_group'. 
    op.drop_table('expense_group')

    # ### end Alembic commands ###


def downgrade():
    # Mantenha a função downgrade como estava, pois ela reverte a lógica original,
    # que é a lógica padrão do Alembic, e não contém as operações manuais de renomeação.
    # O Alembic deve ser capaz de fazer o downgrade de forma reversa.
    # Se der erro, precisará de correção manual no downgrade também.
    
    # Exemplo de como a função downgrade original se comportaria:
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'expense_item', ['item_id'], ['id'])
        batch_op.drop_column('category_id')

    op.create_table('expense_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['expense_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense_group',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('transfer')
    op.drop_table('expense_category')
    # ### end Alembic commands ###
