"""Adicao de campos admin e controle de acesso ao User

Revision ID: 6d1ad4eb1ae4
Revises: a460c5be3bbb
Create Date: 2025-12-11 16:11:11.495096

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import expression

# revision identifiers, used by Alembic.
revision = '6d1ad4eb1ae4'
down_revision = 'a460c5be3bbb'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Adicionar as colunas. is_admin é adicionada como nullable=True, temporariamente.
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Adiciona is_admin como nullable=True (CRÍTICO para o SQLite)
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        
        # Adiciona as outras colunas (Não problemáticas, mas incluídas na transação)
        batch_op.add_column(sa.Column('access_due_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('pending_message', sa.String(length=500), nullable=True))

    # 2. Preencher os valores NULL de is_admin com False (0) para todas as linhas existentes.
    # Isso deve ser feito FORA do bloco op.batch_alter_table em alguns ambientes, mas é mais confiável como op.execute.
    op.execute("UPDATE user SET is_admin = 0 WHERE is_admin IS NULL") 

    # 3. Alterar a coluna is_admin para NOT NULL e definir o default para novas linhas.
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.Boolean(),
               nullable=False,
               # Define o default (opcional, mas bom para consistência)
               server_default=expression.false()) 
        
        # Remove server_default para permitir que o modelo Python gerencie o default
        batch_op.alter_column('is_admin', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pending_message')
        batch_op.drop_column('access_due_date')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
