"""Adição de Receitas a Receber

Revision ID: a460c5be3bbb
Revises: c85635e6a5bb
Create Date: 2025-12-11 10:18:42.684324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a460c5be3bbb'
down_revision = 'c85635e6a5bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revenue_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('receipt_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_received', sa.Boolean(), nullable=False))
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('is_recurrent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_revenue_transaction_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_revenue_transaction_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_revenue_transaction_is_received'), ['is_received'], unique=False)
        batch_op.create_index(batch_op.f('ix_revenue_transaction_receipt_date'), ['receipt_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revenue_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revenue_transaction_receipt_date'))
        batch_op.drop_index(batch_op.f('ix_revenue_transaction_is_received'))
        batch_op.drop_index(batch_op.f('ix_revenue_transaction_due_date'))
        batch_op.drop_index(batch_op.f('ix_revenue_transaction_date'))
        batch_op.alter_column('is_recurrent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.drop_column('is_received')
        batch_op.drop_column('receipt_date')
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
