"""Coluna last_launch_date

Revision ID: dd6e4b59f215
Revises: 92a3cf26adba
Create Date: 2025-10-19 17:21:51.561026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd6e4b59f215'
down_revision = '92a3cf26adba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_launch_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('last_launch_date')

    # ### end Alembic commands ###
